title: IT Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Mathew's IT Portfolio Blog
permalink: ':title/'
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mathew Titus # add your name
author-img: we-in-rest.jpg # add your photo
about-author: As a Systems Administrator, I excel in deploying endpoints, managing policies in Intune and Active Directory, automating processes, and leveraging technology to enhance reliability and productivity # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: amcomp # add your Github handle
social-linkedin: mathew-titus # add your Linkedin handle
social-email: mathew.titus@outlook.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
